// auto-generated by the wand of creation
void create() {
}
int move(mixed dest) {
    return move_object(dest);
}
string short() { return "rusty gear"; }
string long() { return "rusty gear, freshly created by the wand of creation.\n"; }
int id(string arg) { return arg == "rusty gear"; }
